### ISSUE TITLE
403 Forbidden error when using NFS on MacOS Catalina

### ISSUE THREAD

**Issue by anthonyvdberghe** [scotch-io/scotch-box#421]
Hi,

I'm experiencing difficulties setting up the NFS on my MacOS Catalina. Everything is working fine on the default settings, I can browse my site, access MySQL etc..

When reloading the server with NFS enabled everything installs fine, I input the admin password when asked for and the installation is completed, however when I try to reach my website it gives me a 403 forbidden error.

During install I did get the following message, however I'm not sure if this has anything to do about it:

```
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 5.2.6
    default: VirtualBox Version: 6.1
```

Thank you in advance for your help
